version: "2.4"

services:
  registration_api:
    entrypoint: /bin/true
  analytics_feed:
    entrypoint: /bin/true
  nginx:
    entrypoint: /bin/true
  notification-service:
    entrypoint: /bin/true
  digilocker_support_api:
    entrypoint: /bin/true
  flagr:
    entrypoint: /bin/true
  clickhouse-server:
    entrypoint: /bin/true
  keycloak:
    environment:
      - KEYCLOAK_IMPORT=/config/e2e-divoc-realm.json
    volumes:
      - ./keycloak:/config
  certificate_processor:
      environment:
        ADMIN_API_CLIENT_SECRET: 8eb72e25-baff-4ec5-b636-d4c1b55257b5
  e2e_test:
    build:
      context: ./e2e
    container_name: e2e_test
    depends_on:
      vaccination_api:
        condition: service_started
      keycloak:
        condition: service_healthy
      registry:
        condition: service_started
  e2e_api_test:
    build:
      context: ./e2e_api
    container_name: e2e_api_test
    depends_on:
      portal_api:
        condition: service_started
      keycloak:
        condition: service_healthy
      registry:
        condition: service_started
