name: Docker Image CI

on:
  push:
    branches: [ main, orchestration ]
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches: [ main, orchestration ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: make
      - name: Test
        run: make test

  cypress-run:
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./e2e_api
    container: cypress/included:6.6.0
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v2
      - name: Install dependencies 📦
        uses: bahmutov/npm-install@v1
      - name: Run tests 🧪
        run: cypress run
