name: Docker Image CI

on:
  push:
    branches: [ main, orchestration ]
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches: [ main, orchestration ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: make

      - uses: actions/setup-node@v2
      - name: Test API
        run: make test | npm install cypress | npx cypress run --headless
